from Adafruit_Thermal import *
import gfx.logo2b as logo2b

printer = Adafruit_Thermal("/dev/serial0", 19200, timeout=5)


printer.setSize('S')
printer.justify('C') #now the ticket is being printed
printer.println("--------------------------------")
printer.feed(1)
printer.printBitmap(logo2b.width, logo2b.height, logo2b.data)
printer.feed(1)
printer.inverseOn()
printer.println("  Ticket de venta/servicio  ")
printer.inverseOff()
printer.feed(1)
printer.println("================================")
printer.justify('L')
#printer.println("  ID  CANTIDAD  PRECIO  SUBTOTAL")
printer.println("Consulta el detalle de tu pedido")
printer.println("ingresando a tu cuenta en linea.")
printer.println("Obten tu nota en formato PDF.   ")
printer.println("================================")
#printer.println("              DESCUENTO:  $20.00")
#printer.println("--------------------------------")
printer.justify('R')
printer.underlineOn()
printer.println("Total: $100.00")
printer.underlineOff()
printer.feed(1)
printer.justify('L')
printer.println("Numero de pedido: ")
printer.printBarcode("VTHINFRNQ",printer.CODE93)
printer.justify('C')
printer.boldOn()
printer.println("GRACIAS POR TU COMPRA!")
printer.boldOff()
printer.println("www.2brobots.com")
printer.feed(1)
printer.println("------ REV:2A07012015DAFR ------")
printer.feed(3)
